-- +migrate Up
CREATE TYPE "domain" AS ENUM('com', 'me', 'net', 'es', 'kr', 'pro');

DROP TABLE categories;
CREATE TABLE categories (
  domain "domain" NOT NULL,
  label TEXT NOT NULL,
  "order" INT NOT NULL,
  localization_key TEXT NOT NULL,
  PRIMARY KEY (domain, label)
);

-- +migrate Down
DROP TABLE categories;
DROP TYPE "domain";
CREATE TABLE categories (
  alias TEXT PRIMARY KEY,
  name TEXT NOT NULL ,
  "order" INT NOT NULL DEFAULT 0
);
INSERT INTO categories(name, alias, "order") VALUES
  ('Football', 'football', '1'),
  ('Soccer', 'soccer', '2'),
  ('Cricket', 'cricket', '3'),
  ('NFL', 'nfl', '4'),
  ('NHL', 'nhl', '5'),
  ('AFL', 'afl', '6'),
  ('Boxing', 'boxing', '7'),
  ('PBA', 'pba', '8'),
  ('Rugby', 'rugby', '9'),
  ('Basketball', 'basketball', '10'),
  ('Horse Racing', 'horse-racing', '11'),
  ('Cycling', 'cycling', '12'),
  ('Baseball', 'baseball', '13'),
  ('Tennis', 'tennis', '14'),
  ('MLB', 'mlb', '15'),
  ('Hockey', 'hockey', '16'),
  ('Athletics', 'athletics', '17'),
  ('NBA', 'nba', '18'),
  ('Table Tennis', 'table-tennis', '19'),
  ('F1', 'f1', '20'),
  ('Volleyball', 'volleyball', '21'),
  ('Badminton', 'badminton', '22'),
  ('NCAA', 'ncaa', '23'),
  ('MotoGP', 'motogp', '24'),
  ('WWE', 'wwe', '25'),
  ('Golf', 'golf', '26'),
  ('UAAP', 'uaap', '27'),
  ('NASCAR', 'nascar', '28'),
  ('Kabaddi', 'kabaddi', '29'),
  ('Chess', 'chess', '30'),
  ('Martial arts', 'martial-arts', '31'),
  ('Motorsport', 'motorsport', '32'),
  ('Field Hockey', 'field-hockey', '33'),
  ('UFC', 'ufc', '34'),
  ('MMA', 'mma', '35'),
  ('Handball', 'handball', '36'),
  ('Surfing', 'surfing', '37'),
  ('Curling', 'curling', '38'),
  ('Snooker', 'snooker', '39'),
  ('CFL', 'cfl', '40'),
  ('Darts', 'darts', '41'),
  ('Weightlifting', 'weightlifting', '42'),
  ('Billiards', 'billiards', '43'),
  ('Swimming', 'swimming', '44'),
  ('Wrestling', 'wrestling', '45'),
  ('X Games', 'x-games', '46'),
  ('Auto Racing', 'auto-racing', '47'),
  ('Futsal', 'futsal', '48'),
  ('Netball', 'netball', '49'),
  ('Gymnastics', 'gymnastics', '50'),
  ('Padbol', 'padbol', '51'),
  ('Softball', 'softball', '52'),
  ('Ice Hockey', 'ice-hockey', '53'),
  ('Polo', 'polo', '54'),
  ('Sailing', 'sailing', '55'),
  ('Shooting', 'shooting', '56'),
  ('Padel', 'padel', '57'),
  ('Extreme Sports', 'extreme-sports', '58'),
  ('Winter Sports', 'winter-sports', '59'),
  ('Ski', 'ski', '60'),
  ('Diving', 'diving', '61'),
  ('Equestrian', 'equestrian', '62'),
  ('Greyhounds', 'greyhounds', '63'),
  ('Sepak Takraw', 'sepak-takraw', '64'),
  ('Dragon Boat Racing', 'dragon-boat racing', '65'),
  ('Lacrosse', 'lacrosse', '66'),
  ('Roller Hockey', 'roller-hockey', '67'),
  ('Bowling', 'bowling', '68'),
  ('Speedway', 'speedway', '69');
