variables:
  GO_PROJECT: gitlab.scorum.com/blog/api
  GOPATH: /home/gitlab-runner/runner2/go

stages:
  - build_and_test

build_and_test_job:
  stage: build_and_test
  script:
    - rm -rf ${GOPATH}/src/${GO_PROJECT}
    - mkdir -p ${GOPATH}/src/${GO_PROJECT}/
    - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}
    - cd ${GOPATH}/src/${GO_PROJECT}
    - dep ensure -v -vendor-only
    - if [ ! -f /usr/local/lib/libsecp256k1.a ]; then cd verify/c-secp256k1 && ./autogen.sh && ./configure --enable-module-recovery && sudo make install && cd ../../; fi
    - if [ ! -f ${GOPATH}/src/${GO_PROJECT}/verify/c-secp256k1/.libs/libsecp256k1.a ]; then cd verify/c-secp256k1 && ./autogen.sh && ./configure --enable-module-recovery &&  make && cd ../../; fi
    - go build
    - go test -v ./...
  tags:
    - node
